<a href="https://colab.research.google.com/github/linhvuueh/-10-3-VU-PHUONG-LINH---31241023210/blob/main/%5BCIFAR_10%5D_VU_PHUONG_LINH_31241023210.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from re import X
from keras.datasets import cifar10
(X_train,y_train),(X_test,y_test)=cifar10.load_data()
X_train=X_train.reshape(50000,32*32*3)
X_train=X_train.astype('float32')/255
X_test=X_test.reshape(10000,32*32*3)
X_test=X_test.astype('float32')/255
from keras.utils import to_categorical
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)
model = Sequential()
model.add(Dense(512, input_shape=(3072,), activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(112, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
history = model.fit(X_train, y_train, epochs=45, batch_size=64, validation_data=(X_test, y_test))

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 512)                 │       1,573,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 112)                 │          28,784 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │           1,130 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,734,618 (6.62 MB)

 Trainable params: 1,734,618 (6.62 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 31s 37ms/step - accuracy: 0.2794 - loss: 1.9902 - val_accuracy: 0.3811 - val_loss: 1.7432
Epoch 2/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 30s 39ms/step - accuracy: 0.3901 - loss: 1.6955 - val_accuracy: 0.4314 - val_loss: 1.5941
Epoch 3/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 34s 30ms/step - accuracy: 0.4315 - loss: 1.5872 - val_accuracy: 0.4452 - val_loss: 1.5522
Epoch 4/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 30ms/step - accuracy: 0.4461 - loss: 1.5357 - val_accuracy: 0.4438 - val_loss: 1.5653
Epoch 5/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 30ms/step - accuracy: 0.4660 - loss: 1.4971 - val_accuracy: 0.4561 - val_loss: 1.5220
Epoch 6/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 40s 29ms/step - accuracy: 0.4825 - loss: 1.4394 - val_accuracy: 0.4750 - val_loss: 1.4808
Epoch 7/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 30ms/step - accuracy: 0.4915 - loss: 1.4211 - val_accuracy: 0.4659 - val_loss: 1.4856
Epoch 8/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 30ms/step - accuracy: 0.5011 - loss: 1.3992 - 

In [4]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/mclaren-750s-driving-dynamic-hero-1920x774px.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([1])

In [8]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/BTGBG23-RUN-Starcraft-SVX-230-IO-03-edit.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step


array([8])

In [9]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/Truck-la-gi.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([9])

In [11]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/pngtree-breed-dog-animal-png-image_11544061.png',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([5])

In [12]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/438159401-Prothonotary_Warbler-Ryan_Justice-social.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([2])

In [13]:

from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/images (2).jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


array([4])

In [14]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/220325case013.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


array([3])

In [16]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/ThinChestnutHorseGrazing_AdobeStock_811395577.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([7])

In [18]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/Water-holding-frog-scaled.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([6])

In [19]:
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/221216150405-c919a.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([0])