<a href="https://colab.research.google.com/github/linhvuueh/-10-3-VU-PHUONG-LINH---31241023210/blob/main/%5BCIFAR_100%5D_VU_PHUONG_LINH_31241023210.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from re import X
from keras.datasets import cifar100
(X_train,y_train),(X_test,y_test)=cifar100.load_data()
X_train=X_train.reshape(50000,32*32*3)
X_train=X_train.astype('float32')/255
X_test=X_test.reshape(10000,32*32*3)
X_test=X_test.astype('float32')/255
from keras.utils import to_categorical
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
y_train=to_categorical(y_train)
y_test=to_categorical(y_test)
model = Sequential()
model.add(Dense(512, input_shape=(3072,), activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(112, activation='relu'))
model.add(Dense(100, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()
history = model.fit(X_train, y_train, epochs=45, batch_size=64, validation_data=(X_test, y_test))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                      │ (None, 512)                 │       1,573,376 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 112)                 │          28,784 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 100)                 │          11,300 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,744,788 (6.66 MB)

 Trainable params: 1,744,788 (6.66 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 26s 31ms/step - accuracy: 0.0250 - loss: 4.4873 - val_accuracy: 0.0808 - val_loss: 3.9965
Epoch 2/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 23s 30ms/step - accuracy: 0.0881 - loss: 3.9308 - val_accuracy: 0.1036 - val_loss: 3.8752
Epoch 3/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 42s 31ms/step - accuracy: 0.1261 - loss: 3.7293 - val_accuracy: 0.1480 - val_loss: 3.6350
Epoch 4/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 24s 31ms/step - accuracy: 0.1500 - loss: 3.5816 - val_accuracy: 0.1569 - val_loss: 3.5921
Epoch 5/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 25s 31ms/step - accuracy: 0.1718 - loss: 3.4767 - val_accuracy: 0.1736 - val_loss: 3.5178
Epoch 6/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 40s 31ms/step - accuracy: 0.1852 - loss: 3.4008 - val_accuracy: 0.1699 - val_loss: 3.4984
Epoch 7/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 41s 31ms/step - accuracy: 0.1978 - loss: 3.3256 - val_accuracy: 0.1737 - val_loss: 3.4834
Epoch 8/45
782/782 ━━━━━━━━━━━━━━━━━━━━ 40s 30ms/step - accuracy: 0.2013 - loss: 3.2992 - 

In [20]:
#CAMEL
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/images (2).jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([15])

In [21]:
#BICYCLE
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/roll-bicycle-company-c1-city-bike-step-thru-405434-12.png',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


array([8])

In [22]:
#CHAIR
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/foundations-little-scholars-kids-school-chairs-12-in-seat-height_main_1.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([20])

In [24]:
#ELEPHANT
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/AboutElephant-Savanna.jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([31])

In [26]:
#lion
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/images (4).jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([43])

In [29]:
#orange
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/fresh-orange.png',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([53])

In [30]:
#crab
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/images (6).jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([26])

In [34]:
#forest
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/cropped-forests.jpeg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([33])

In [36]:
#girl
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/beautiful-smiling-girl-with-long-braided-hair-in-a-sweater-photo.jpeg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([35])

In [37]:
#rocket
from keras.utils import to_categorical
from keras.utils import img_to_array
from keras.preprocessing.image import load_img
img = load_img('/content/images (7).jpg',target_size=(32,32))
img=img_to_array(img)
img=img.reshape(1,32*32*3)
img=img.astype('float32')/255.0
import numpy as np
np.argmax(model.predict(img),axis=-1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([69])